### ISSUE TITLE
Fiddle example using rivets.js is broken

### ISSUE THREAD

**Issue by kokujin** [pluma/obs#5]
Hi there! The fiddle example does not work anymore. Tested in latest Chrome and Firefox

**Comment by pluma** [comment]
Thanks for the heads up. Seems the API changed in rivets 0.6. I've updated the example with the dependency pinned on 0.5.13 for now.

**Comment by kokujin** [comment]
Great. This has no effect on the library? I can use the adapter without problems?

**Comment by pluma** [comment]
Obs has no dependency on rivets, so it continues to work as expected. If you want to use it with rivets you either need to use rivets 0.5.x if you want to follow the example or find out how to use obs with the current version of rivets (shouldn't be difficult, I just don't have the time right now to try it out).

If you do find out why the example no longer works with rivets 0.6, I'd love to hear from you so I can update the example to the most recent version.
